---
swagger: "2.0"
info:
  description: "Implementación de servicio Core de ingesta de datos recibidos de dispositivos\
    \ Sigfox\n[http://swagger.io](http://swagger.io) or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: 1.0.0
  title: Sigfox Service
  termsOfService: http://swagger.io/terms/
  contact:
    email: marcosrivas17@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
host: virtserver.swaggerhub.com
basePath: /Crowdynamics/SigfoxService/1.0.0
tags:
- name: Mensaje Sigfox
  description: Mensaje enviado por los dispositivos geolocalizables
  externalDocs:
    description: Find out more
    url: http://swagger.io
schemes:
- https
- http
paths:
  /message:
    post:
      tags:
      - Mensaje Sigfox
      summary: Registrar nuevo mensaje sigfox
      operationId: addSigfoxMessage
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - in: body
        name: body
        description: Mensaje que debe ser registrado en el sistema
        required: true
        schema:
          $ref: '#/definitions/SigfoxMessage'
      responses:
        200:
          description: Mensaje Registrado
          schema:
            $ref: '#/definitions/SigfoxMessage'
        400:
          description: Datos de entrada invalidos
  /message/{deviceId}:
    get:
      tags:
      - Mensaje Sigfox
      summary: Obtener mensajes enviados por el dispositivo indicado
      description: Returns a single pet
      operationId: getSigfoxMessageByDeviceId
      produces:
      - application/json
      parameters:
      - name: deviceId
        in: path
        description: ID del dispositivo del que obtener mensajes
        required: true
        type: string
      responses:
        200:
          description: Datos encontrados
          schema:
            type: array
            items:
              $ref: '#/definitions/SigfoxMessage'
        400:
          description: Datos de entrada invalidos
        404:
          description: No existen registros de mensajes
definitions:
  SigfoxMessage:
    type: object
    required:
    - deviceId
    properties:
      deviceId:
        type: string
        description: Identificador unico del dispositivo
      time:
        type: string
        description: Momento en el que se envió el mensaje
      segNumber:
        type: string
        description: Numero de secuencia autoincremental
      reception:
        $ref: '#/definitions/ReceptionMessage'
      geoloc:
        $ref: '#/definitions/GeolocData'
    example:
      geoloc:
        latitude: latitude
        raDIUS: raDIUS
        longitude: longitude
      segNumber: segNumber
      time: time
      reception:
        rssi: rssi
        snr: snr
        id: id
      deviceId: deviceId
  ReceptionMessage:
    type: object
    properties:
      id:
        type: string
        description: Identificador unico de recepción
      rssi:
        type: string
        description: Nivel de señal
      snr:
        type: string
        description: Relación señal a ruido
    example:
      rssi: rssi
      snr: snr
      id: id
  GeolocData:
    type: object
    properties:
      latitude:
        type: string
        description: Latitud
      longitude:
        type: string
        description: Longitud
      raDIUS:
        type: string
        description: Radio de error
    example:
      latitude: latitude
      raDIUS: raDIUS
      longitude: longitude
