spring:
  jpa: 
    database: POSTGRESQL
    show-sql: true
    hibernate.dll-auto: update
  datasource:
    platform: postgres
    url: jdbc:postgres://ec2-54-75-244-248.eu-west-1.compute.amazonaws.com:5432/d9n4pkcd0ismmi?ssl=true&sslfactory=org.postgresql.ssl.NonValidatingFactory
    driverClassName: org.postgresql.Driver
    username: postgres
    password: admin   
server:
    port: 8080